package com.giovannip.noticeme.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NoteAccessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoteAccessAllPropertiesEquals(NoteAccess expected, NoteAccess actual) {
        assertNoteAccessAutoGeneratedPropertiesEquals(expected, actual);
        assertNoteAccessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoteAccessAllUpdatablePropertiesEquals(NoteAccess expected, NoteAccess actual) {
        assertNoteAccessUpdatableFieldsEquals(expected, actual);
        assertNoteAccessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoteAccessAutoGeneratedPropertiesEquals(NoteAccess expected, NoteAccess actual) {
        assertThat(actual)
            .as("Verify NoteAccess auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoteAccessUpdatableFieldsEquals(NoteAccess expected, NoteAccess actual) {
        assertThat(actual)
            .as("Verify NoteAccess relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoteAccessUpdatableRelationshipsEquals(NoteAccess expected, NoteAccess actual) {
        assertThat(actual)
            .as("Verify NoteAccess relationships")
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }
}
